// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt8BQJUTbf_aA17a8cKh6tJtzWe-JYMq4',
    appId: '1:233424766256:android:6b9bf6c3bf901a576df4f5', 
     databaseURL: "https://eldaversion10.firebase.com",
    messagingSenderId: '233424766256',  
    projectId: 'eldaversion10',
    authDomain: 'eldaversion10.firebaseapp.com',
    storageBucket: 'eldaversion10.appspot.com',
    // measurementId: 'G-HDFV36VDNC', //not done
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8BQJUTbf_aA17a8cKh6tJtzWe-JYMq4',
    appId: '1:233424766256:android:6b9bf6c3bf901a576df4f5', 
     databaseURL: "https://eldaversion10.firebase.com",
    messagingSenderId: '233424766256',
    projectId: 'eldaversion10',
    storageBucket: 'eldaversion10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8BQJUTbf_aA17a8cKh6tJtzWe-JYMq4',
    appId: '1:233424766256:android:6b9bf6c3bf901a576df4f5',  
     databaseURL: "https://eldaversion10.firebase.com",
    messagingSenderId: '233424766256', 
    projectId: 'eldaversion10',
    storageBucket: 'eldaversion10.appspot.com',
    iosBundleId: 'com.example.medtrack',
  );

}
